export const INPUT_FOCUS = 'header/input_focus'
export const INPUT_BLUR = 'header/input_blur'
export const INIT_LIST = 'header/init_list'
export const MOUSE_ENTER = 'header/mouse_enter'
export const MOUSE_LEAVE = 'header/mouse_leave'
export const CHANGE_LIST = 'header/change_list'
